service: wallmasters-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: me-south-1
  environment:
    CONNECTION_STRING: ${env:CONNECTION_STRING}
    JWT_SECRET: ${env:JWT_SECRET}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    NODE_ENV: production

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      NODE_ENV: production

custom:
  cors:
    origin: "*"
    headers:
      - Content-Type
      - Authorization
      - X-Amz-Date
      - X-Api-Key
      - X-Amz-Security-Token

plugins:
  - serverless-offline
